### Rules

1. Please read the instructions and problem prompts **carefully**.
2. This lab is to give you understanding of data structures like list, queue, dictionary, heap along with the usage of numpy. Besides, some topics such as how to make your jupyter notebook be a more efficient developing tools, how to use git and GitHub will also be covered. The lab is to be done individually. You may talk to your fellow classmates about general issues ("Remind me again: Which API should I used for doing group by operation to a data set") but about the specifies of how to do these exercises.
3. Along with a similar vein, you can ask the TA for help, but ask questions about **concepts** but not ask the TA to help you debug your code. The TA is here to help, but not to do the work for you.
4. You are welcome to use the class resources and the Internet.
5. Playing with variations. Solve one problems, and then copy the code to a new cell and play around with it. Doing this is the single most important thing when learning programming.
6. This lab will not be graded but the content is highly related to your future programming assignments. So, treat it wisely.
7. All the content having been gone though in the week 1 discussion is just a snapshot of the most basic concepts. **You need to keep study more about Git, GitHub, and Numpy in order to finish your programming assignments successfully.**
8. Have fun!

<center><h1>CSCI 360 Lab 0</h1></center>
<br>
<center><font size="4">Introduction to Artificial Intelligence</font></center>

### Setup Development Environment

There are many ways to setup the environment. But, I do recommend a simple idea that is using the Anaconda, which is a pre-build python environment with bundles of useful packages.

**To download the Anaconda, go to the following website:
https://www.anaconda.com/distribution/**. Download the correct version based on your operating system and install it step by step.

Then, **configure your PATH environment variable** to make the conda command work. The following command is an easy way to test whether your configuration is correct. If it is, you will see something as like as the sample output.

> **command:**
>
> conda --version
>
> **sample output:**
>
> conda 4.6.12

**Finally, download this jupyter notebook file,** then change the working directory to where its location in terminal, and type the following command to open the jupter notebook and finish the lab.

> **command:** 
> jupyter notebook

In [2]:
import numpy as np

### Lists

#### Basic List Functions





*   Read this [documentation](https://docs.python.org/3/tutorial/datastructures.html) to get acquainted with the available list functions 
*   Define a list players with elements 
  *   Federer
  *   Nadal
  *   Felix
*   Append Djokovic, Medvedev and  Sinner into the list
*   Define a list new_players with elements
  *   Tsitsipas
  *   Rublev
  *   Dimitrov
*   Merge the new_players list into the players list
*   Remove Medvedev from the players list

In [6]:
players = ["Federer", "Nadal", "Felix"]

players.append("Djokovic")
players.append("Medvedev")
players.append("Sinner")

new_players = ["Tsitsipas", "Rublev", "Dimitrov"]

for player in new_players: 
    players.append(player)
    
players.remove("Medvedev")

for player in players: 
    print(player)


Federer
Nadal
Felix
Djokovic
Sinner
Tsitsipas
Rublev
Dimitrov


####Indexing and Slicing






*   Read this [tutorial](https://realpython.com/lessons/indexing-and-slicing/) to learn about indexing and slicing.
*   Use negative indexing to access the last element of the players list.
*   Create a new list which only has the last 3 elements from the players list. 
*   Check out and play with different ways to index and slice the list.

In [10]:
players[-1]
print(players[-1])

new_list = players[-3:]
print(new_list)

Dimitrov
['Tsitsipas', 'Rublev', 'Dimitrov']


####List Comprehension


List comprehension is an elegant way to define and create lists based on existing lists. List comprehension is generally more compact and faster than normal functions and loops for creating list.

*   Read this [tutorial](https://www.w3schools.com/python/python_lists_comprehension.asp) to learn about list comprehension.
*   Use list comprehension to create a list of squares of all the odd numbers between 50 and 100.
*   Use list comprehension to create a filtered_players list from the players list, which contains all the players having the vowel e in their name. [Example : Federer]



#### Some Other List Functions


*   Explore min(), max(), sum(), len(), sort() functions.
*   Define a list with numbers [1, 37, 2, 59, 46, 32, 12, 40, 78].
*   Sort the list in descending order. 
    
    **Hint:** Use key/reverse parameter of the sort function
*   Print the sum, min, max, mean and median of this list.







### Queues


Queue in Python can be implemented by the following ways:
 

* list : Instead of enqueue() and dequeue(), append() and pop() function is used. However, lists are quite slow for this purpose because inserting or deleting an element at the beginning requires shifting all of the other elements by one, requiring O(n) time.

* collections.deque : deque provides an O(1) time complexity for append and pop operations as compared to list which provides O(n) time complexity. Instead of enqueue and deque, append() and popleft() functions are used.

***NOTE***: deque is a different data structure than the conventional queues in the sense that it is known is 'double ended queue', but we can use this data structure to run queue operations efficiently.

* queue.Queue : Queue is built-in module of Python which is used to implement a queue. queue.Queue(maxsize) initializes a variable to a maximum size of maxsize. A maxsize of zero ‘0’ means a infinite queue. This Queue follows FIFO rule. 

[Read the documentation of deque here](https://docs.python.org/3/library/collections.html#collections.deque)

[Read the documentation of python queue class here](https://docs.python.org/3/library/queue.html)


Read the documentations and choose one of above two implementations for the following exercises.

Exercise:

* Create a queue with the following elements in the given order: [2, -1, 3, 4, -1, 5, 6, 7, -1, 8, 9, 10, -1 , -1]
* Write a function reOrg(), that takes the above queue as an argument and returns a list of lists containing all contiguous positive elements in the queue, for example, for the given queue, you need to output [[2], [3,4], [5,6,7], [8,9,10]].

Hint : Use a while loop with condition (!isEmpty(queue)), create a global list, create smaller lists inside the loop and work on getting the desired output. You'll need to use the methods push(), pop(), front() in order to solve the problem. 

Exercise:
https://leetcode.com/problems/implement-stack-using-queues/

### Dictionary

General Syntax:

A general dictionary in Python looks something like this:
```python
>>> dictionary_name = {key_1: value_1,
                   key_2: value_2,
                   key_3: value_3,
                   }
```



Add/modify a key-value pair to a dictionary:

```python
>>> dictionary_name['key'] = value
```


**EXERCISE**

Now, create an empty dictionary
* Define a dictionary with the following data pairs
   * John - Cena
   * Jack - Ma
   * Jill - Goodacre
* Add "Jennifer" to the dictionary the with the value "Aniston"
* Then remove Jill from the dictionary.
* Modify Jennifer's value from Aniston to Lawrence in the dictionary.


We can use the following methods:

* `dict.items()` : List of all key-value pairs 
* `dict.keys()` : list of all the keys in a dictionary

* `dict.values()` : list of all the values in a dictionary

* `dict.clear()` : Remove all items

* `dict.copy()` : Returns a shallow copy of a dictionary

* `dict.get(x)` : Returns value from key x


**LOOPING** through all the elements in a dictionary:
```python
for key_name, value_name in dictionary_name.items():
    print(key_name) # The key is stored in whatever you called the first variable.
    print(value_name) # The value associated with that key is stored in your second variable.
```


**EXERCISE**
* Create a ***dictionary of lists*** for the following data
* A student can have upto 5 courses' scores.

| studentID | AI | ML | OS | WebTech | Algo |
| ----- | --- | ----| ----| ----| ----|
| 1001| 95 | 93 | 81 | 90 | 100 | 
| 1002 | 100 | 95 | 89 | 87 | |
| 1003 | 92 | 91 |  | 80 | | |


* Print the full dictionary
* Print all the student IDs in the dictionary
* Print all scores for student 1003
* Delete all scores for student 1001
* Print the full dictionary

Hint: Use studentID as key and value as a list of scores.

**EXERCISE**
* Create the following dictionary
``` 
patient = {
    'bmi' : 30,
    'diagnosis' : ['Schizophrenia', 'Diabetes', 'Anxiety'],
    'heart_rates' : [95, 123, 135, 91, 175, 2000]
}
```
* Add a key to the dictionary called 'medication'.
* Set the value of 'medication' to be a list consisting of the strings 'Aripiprazole', 'Citalopram', and 'Ibuprofen'.
* .sort() the measures in the list stored under the 'heart_rates' key.
* Then .remove() 2000 from the list of 'heart_rates'.
* Add the value 5 to the number stored under the 'bmi' key.
* Print the full dictionary

### Heap

The heapq module in python provides the different functions required to maintain the heap data structure. The heap is maintained in a python list and we use the functions provided by heapq to maintain the required heap property in the list.

**Quick start:** https://docs.python.org/3/library/heapq.html

#### Basic Heap Operations

*   Create a list with numbers [22, 37, 90, 49, 56, 65].
*   Use heapify to convert the list into a min heap.
*   Use heappush to add the numbers 12, 40, 99 into the list.
*   Use heappop 4 times and print those numbers.
*   Play with the heap functions to get more acquainted.



####Max Heap

Solve the above exercise again by considering a max heap, instead of a min heap. Note that the heapq library by default provides min heap. 
**Hint:** Store numbers as negative (e.g. -1 instead of 1)

#### Heap Sort

Use the heap functions to create a sorted list from the above given list. Note that this approach is similar to the famous sorting algorithm called heap sort.



### Numpy

Quick start: https://www.numpy.org/devdocs/user/quickstart.html

Numpy axes explaination: https://www.sharpsightlabs.com/blog/numpy-axes-explained/

#### The np.array Method

Example 1:

```python
ls = [1, 2, 3]
arr = np.array(ls)
```

Example 2:
```python
>>> np.array([[1, 2], [3, 4]])
array([[1, 2],
       [3, 4]])
```

Now, create a 2-dimensional Python list object, then convert it to a Numpy array object.

#### ndarray Objects' Attributes

Play with the **ndim, shape, size, dtype, itemsize and data** attribute.

Example:

```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.ndim
2
```

#### Dimension of ndarray Ojects

Play with the reshape() and flatten() method.

Example:
```python
>>> arr = np.array([[1, 2], [3, 4]])
>>> arr.flatten()
array([1, 2, 3, 4])
```

#### The Slice Operation of ndarray Objects

Understand how the slice operation works for 1-D array and 2-D array.

Example:

```python
>>> arr = np.array([[1, 2, 3], [3, 4, 6], [7, 8, 9]])
>>> arr[1:]
array([[3, 4, 6],
       [7, 8, 9]])
>>> arr[1:, 0:2]
array([[3, 4],
       [7, 8]])
```

#### The Calculation of ndarray Objects

Play with the **argmin(), argmax(), min(), max(), mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), mod()** method.

Example:

```python
>>> np.square(array)
array([[ 1,  4,  9],
       [ 9, 16, 36],
       [49, 64, 81]])

```

#### Other Important Methods Inside Module Numpy

Play with the arange(), ones(), zeros(), eye(), linspace(), concatenate() method.

Example:

```python
>>> np.eye(3)
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
```

While arrays in C++ have a fixed size and are homogeneous (store the same type of data), lists in python are resizable and can store different types of data including lists itself (nested lists).

General Syntax:

A general list in Python looks something like this:
```python
>>> list_name = ['A', 'B', 'C']
```

**LOOPING** through the list:
```python
>>> for item_name in list_name:
      print(item_name)
```

### Jupyter Notebook

#### Jupyter Notebook Extensions

Extensions such as the code formatter, table of content is to make your development more efficient. To explore it, please refer to https://github.com/ipython-contrib/jupyter_contrib_nbextensions.

#### Jupyter Visual Debugger

The Pixie Debugger is a visual debugger for debugging on Jupyter Notebook. To explore it, please refer to https://medium.com/codait/the-visual-python-debugger-for-jupyter-notebooks-youve-always-wanted-761713babc62.

### Git and GitHub

1. In the directory that where this jupyter notebook file locates in, init a Git repository.
2. Checkout a new branch called dev and commit the current notebook within this branch.
3. Merge the dev branch to the master branch (the default branch).
4. Create a temporary repository (just for practicing and you can delete it later) in GitHub. 
5. Push new changes in the master branch to the remote repository created in step 4.
6. Checkout the dev branch again and do some changes to your notebook, and then repeat step 3 and step 5.